//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.26 at 11:46:58 PM GMT+01:00 
//


package com.example.order_management.orders;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.order_management.orders package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.order_management.orders
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetOrderRequest }
     * 
     */
    public GetOrderRequest createGetOrderRequest() {
        return new GetOrderRequest();
    }

    /**
     * Create an instance of {@link GetOrderResponse }
     * 
     */
    public GetOrderResponse createGetOrderResponse() {
        return new GetOrderResponse();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link GetOrdersByClientRequest }
     * 
     */
    public GetOrdersByClientRequest createGetOrdersByClientRequest() {
        return new GetOrdersByClientRequest();
    }

    /**
     * Create an instance of {@link GetOrdersByClientResponse }
     * 
     */
    public GetOrdersByClientResponse createGetOrdersByClientResponse() {
        return new GetOrdersByClientResponse();
    }

    /**
     * Create an instance of {@link CalculateOrderTotalRequest }
     * 
     */
    public CalculateOrderTotalRequest createCalculateOrderTotalRequest() {
        return new CalculateOrderTotalRequest();
    }

    /**
     * Create an instance of {@link CalculateOrderTotalResponse }
     * 
     */
    public CalculateOrderTotalResponse createCalculateOrderTotalResponse() {
        return new CalculateOrderTotalResponse();
    }

    /**
     * Create an instance of {@link UpdateOrderStatusRequest }
     * 
     */
    public UpdateOrderStatusRequest createUpdateOrderStatusRequest() {
        return new UpdateOrderStatusRequest();
    }

    /**
     * Create an instance of {@link UpdateOrderStatusResponse }
     * 
     */
    public UpdateOrderStatusResponse createUpdateOrderStatusResponse() {
        return new UpdateOrderStatusResponse();
    }

}
