//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.26 at 11:46:58 PM GMT+01:00 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://example.com/order-management/orders", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.order_management.orders;
