// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public interface NotificationHistoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.NotificationHistoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  java.util.List<com.example.notification.NotificationRecord> 
      getNotificationsList();
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  com.example.notification.NotificationRecord getNotifications(int index);
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  int getNotificationsCount();
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  java.util.List<? extends com.example.notification.NotificationRecordOrBuilder> 
      getNotificationsOrBuilderList();
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  com.example.notification.NotificationRecordOrBuilder getNotificationsOrBuilder(
      int index);
}
