// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public final class NotificationProto {
  private NotificationProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_OrderNotificationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_OrderNotificationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_OrderNotificationResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_OrderNotificationResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationHistoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationHistoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationHistoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationHistoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notification_NotificationRecord_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_notification_NotificationRecord_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022notification.proto\022\014notification\"\241\001\n\030O" +
      "rderNotificationRequest\022\020\n\010order_id\030\001 \001(" +
      "\003\022\021\n\tclient_id\030\002 \001(\003\022\023\n\013client_name\030\003 \001(" +
      "\t\022\024\n\014client_email\030\004 \001(\t\022\024\n\014total_amount\030" +
      "\005 \001(\001\022\016\n\006status\030\006 \001(\t\022\017\n\007message\030\007 \001(\t\"V" +
      "\n\031OrderNotificationResponse\022\017\n\007success\030\001" +
      " \001(\010\022\017\n\007message\030\002 \001(\t\022\027\n\017notification_id" +
      "\030\003 \001(\t\">\n\032NotificationHistoryRequest\022\021\n\t" +
      "client_id\030\001 \001(\003\022\r\n\005limit\030\002 \001(\005\"V\n\033Notifi" +
      "cationHistoryResponse\0227\n\rnotifications\030\001" +
      " \003(\0132 .notification.NotificationRecord\"s" +
      "\n\022NotificationRecord\022\027\n\017notification_id\030" +
      "\001 \001(\t\022\020\n\010order_id\030\002 \001(\003\022\017\n\007message\030\003 \001(\t" +
      "\022\021\n\ttimestamp\030\004 \001(\t\022\016\n\006status\030\005 \001(\t2\356\001\n\023" +
      "NotificationService\022h\n\025SendOrderNotifica" +
      "tion\022&.notification.OrderNotificationReq" +
      "uest\032\'.notification.OrderNotificationRes" +
      "ponse\022m\n\026GetNotificationHistory\022(.notifi" +
      "cation.NotificationHistoryRequest\032).noti" +
      "fication.NotificationHistoryResponseB/\n\030" +
      "com.example.notificationB\021NotificationPr" +
      "otoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_notification_OrderNotificationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_notification_OrderNotificationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_OrderNotificationRequest_descriptor,
        new java.lang.String[] { "OrderId", "ClientId", "ClientName", "ClientEmail", "TotalAmount", "Status", "Message", });
    internal_static_notification_OrderNotificationResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_notification_OrderNotificationResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_OrderNotificationResponse_descriptor,
        new java.lang.String[] { "Success", "Message", "NotificationId", });
    internal_static_notification_NotificationHistoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_notification_NotificationHistoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationHistoryRequest_descriptor,
        new java.lang.String[] { "ClientId", "Limit", });
    internal_static_notification_NotificationHistoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_notification_NotificationHistoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationHistoryResponse_descriptor,
        new java.lang.String[] { "Notifications", });
    internal_static_notification_NotificationRecord_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_notification_NotificationRecord_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_notification_NotificationRecord_descriptor,
        new java.lang.String[] { "NotificationId", "OrderId", "Message", "Timestamp", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
