// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public interface NotificationHistoryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.NotificationHistoryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 client_id = 1;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <code>int32 limit = 2;</code>
   * @return The limit.
   */
  int getLimit();
}
