// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

/**
 * <pre>
 * Response message for notification history
 * </pre>
 *
 * Protobuf type {@code notification.NotificationHistoryResponse}
 */
public final class NotificationHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:notification.NotificationHistoryResponse)
    NotificationHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NotificationHistoryResponse.newBuilder() to construct.
  private NotificationHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NotificationHistoryResponse() {
    notifications_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new NotificationHistoryResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.notification.NotificationProto.internal_static_notification_NotificationHistoryResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.notification.NotificationProto.internal_static_notification_NotificationHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.notification.NotificationHistoryResponse.class, com.example.notification.NotificationHistoryResponse.Builder.class);
  }

  public static final int NOTIFICATIONS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.example.notification.NotificationRecord> notifications_;
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.example.notification.NotificationRecord> getNotificationsList() {
    return notifications_;
  }
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.example.notification.NotificationRecordOrBuilder> 
      getNotificationsOrBuilderList() {
    return notifications_;
  }
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  @java.lang.Override
  public int getNotificationsCount() {
    return notifications_.size();
  }
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  @java.lang.Override
  public com.example.notification.NotificationRecord getNotifications(int index) {
    return notifications_.get(index);
  }
  /**
   * <code>repeated .notification.NotificationRecord notifications = 1;</code>
   */
  @java.lang.Override
  public com.example.notification.NotificationRecordOrBuilder getNotificationsOrBuilder(
      int index) {
    return notifications_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < notifications_.size(); i++) {
      output.writeMessage(1, notifications_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < notifications_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, notifications_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.notification.NotificationHistoryResponse)) {
      return super.equals(obj);
    }
    com.example.notification.NotificationHistoryResponse other = (com.example.notification.NotificationHistoryResponse) obj;

    if (!getNotificationsList()
        .equals(other.getNotificationsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNotificationsCount() > 0) {
      hash = (37 * hash) + NOTIFICATIONS_FIELD_NUMBER;
      hash = (53 * hash) + getNotificationsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.notification.NotificationHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.example.notification.NotificationHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.example.notification.NotificationHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.notification.NotificationHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.notification.NotificationHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Response message for notification history
   * </pre>
   *
   * Protobuf type {@code notification.NotificationHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notification.NotificationHistoryResponse)
      com.example.notification.NotificationHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.notification.NotificationProto.internal_static_notification_NotificationHistoryResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.notification.NotificationProto.internal_static_notification_NotificationHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.notification.NotificationHistoryResponse.class, com.example.notification.NotificationHistoryResponse.Builder.class);
    }

    // Construct using com.example.notification.NotificationHistoryResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (notificationsBuilder_ == null) {
        notifications_ = java.util.Collections.emptyList();
      } else {
        notifications_ = null;
        notificationsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.notification.NotificationProto.internal_static_notification_NotificationHistoryResponse_descriptor;
    }

    @java.lang.Override
    public com.example.notification.NotificationHistoryResponse getDefaultInstanceForType() {
      return com.example.notification.NotificationHistoryResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.notification.NotificationHistoryResponse build() {
      com.example.notification.NotificationHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.notification.NotificationHistoryResponse buildPartial() {
      com.example.notification.NotificationHistoryResponse result = new com.example.notification.NotificationHistoryResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.example.notification.NotificationHistoryResponse result) {
      if (notificationsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          notifications_ = java.util.Collections.unmodifiableList(notifications_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.notifications_ = notifications_;
      } else {
        result.notifications_ = notificationsBuilder_.build();
      }
    }

    private void buildPartial0(com.example.notification.NotificationHistoryResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.notification.NotificationHistoryResponse) {
        return mergeFrom((com.example.notification.NotificationHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.notification.NotificationHistoryResponse other) {
      if (other == com.example.notification.NotificationHistoryResponse.getDefaultInstance()) return this;
      if (notificationsBuilder_ == null) {
        if (!other.notifications_.isEmpty()) {
          if (notifications_.isEmpty()) {
            notifications_ = other.notifications_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureNotificationsIsMutable();
            notifications_.addAll(other.notifications_);
          }
          onChanged();
        }
      } else {
        if (!other.notifications_.isEmpty()) {
          if (notificationsBuilder_.isEmpty()) {
            notificationsBuilder_.dispose();
            notificationsBuilder_ = null;
            notifications_ = other.notifications_;
            bitField0_ = (bitField0_ & ~0x00000001);
            notificationsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getNotificationsFieldBuilder() : null;
          } else {
            notificationsBuilder_.addAllMessages(other.notifications_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.example.notification.NotificationRecord m =
                  input.readMessage(
                      com.example.notification.NotificationRecord.parser(),
                      extensionRegistry);
              if (notificationsBuilder_ == null) {
                ensureNotificationsIsMutable();
                notifications_.add(m);
              } else {
                notificationsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.example.notification.NotificationRecord> notifications_ =
      java.util.Collections.emptyList();
    private void ensureNotificationsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        notifications_ = new java.util.ArrayList<com.example.notification.NotificationRecord>(notifications_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.notification.NotificationRecord, com.example.notification.NotificationRecord.Builder, com.example.notification.NotificationRecordOrBuilder> notificationsBuilder_;

    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public java.util.List<com.example.notification.NotificationRecord> getNotificationsList() {
      if (notificationsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(notifications_);
      } else {
        return notificationsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public int getNotificationsCount() {
      if (notificationsBuilder_ == null) {
        return notifications_.size();
      } else {
        return notificationsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public com.example.notification.NotificationRecord getNotifications(int index) {
      if (notificationsBuilder_ == null) {
        return notifications_.get(index);
      } else {
        return notificationsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder setNotifications(
        int index, com.example.notification.NotificationRecord value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.set(index, value);
        onChanged();
      } else {
        notificationsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder setNotifications(
        int index, com.example.notification.NotificationRecord.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.set(index, builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder addNotifications(com.example.notification.NotificationRecord value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.add(value);
        onChanged();
      } else {
        notificationsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder addNotifications(
        int index, com.example.notification.NotificationRecord value) {
      if (notificationsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureNotificationsIsMutable();
        notifications_.add(index, value);
        onChanged();
      } else {
        notificationsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder addNotifications(
        com.example.notification.NotificationRecord.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.add(builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder addNotifications(
        int index, com.example.notification.NotificationRecord.Builder builderForValue) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.add(index, builderForValue.build());
        onChanged();
      } else {
        notificationsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder addAllNotifications(
        java.lang.Iterable<? extends com.example.notification.NotificationRecord> values) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, notifications_);
        onChanged();
      } else {
        notificationsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder clearNotifications() {
      if (notificationsBuilder_ == null) {
        notifications_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        notificationsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public Builder removeNotifications(int index) {
      if (notificationsBuilder_ == null) {
        ensureNotificationsIsMutable();
        notifications_.remove(index);
        onChanged();
      } else {
        notificationsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public com.example.notification.NotificationRecord.Builder getNotificationsBuilder(
        int index) {
      return getNotificationsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public com.example.notification.NotificationRecordOrBuilder getNotificationsOrBuilder(
        int index) {
      if (notificationsBuilder_ == null) {
        return notifications_.get(index);  } else {
        return notificationsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public java.util.List<? extends com.example.notification.NotificationRecordOrBuilder> 
         getNotificationsOrBuilderList() {
      if (notificationsBuilder_ != null) {
        return notificationsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(notifications_);
      }
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public com.example.notification.NotificationRecord.Builder addNotificationsBuilder() {
      return getNotificationsFieldBuilder().addBuilder(
          com.example.notification.NotificationRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public com.example.notification.NotificationRecord.Builder addNotificationsBuilder(
        int index) {
      return getNotificationsFieldBuilder().addBuilder(
          index, com.example.notification.NotificationRecord.getDefaultInstance());
    }
    /**
     * <code>repeated .notification.NotificationRecord notifications = 1;</code>
     */
    public java.util.List<com.example.notification.NotificationRecord.Builder> 
         getNotificationsBuilderList() {
      return getNotificationsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.example.notification.NotificationRecord, com.example.notification.NotificationRecord.Builder, com.example.notification.NotificationRecordOrBuilder> 
        getNotificationsFieldBuilder() {
      if (notificationsBuilder_ == null) {
        notificationsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.example.notification.NotificationRecord, com.example.notification.NotificationRecord.Builder, com.example.notification.NotificationRecordOrBuilder>(
                notifications_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        notifications_ = null;
      }
      return notificationsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:notification.NotificationHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:notification.NotificationHistoryResponse)
  private static final com.example.notification.NotificationHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.notification.NotificationHistoryResponse();
  }

  public static com.example.notification.NotificationHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NotificationHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<NotificationHistoryResponse>() {
    @java.lang.Override
    public NotificationHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<NotificationHistoryResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NotificationHistoryResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.notification.NotificationHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

