// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public interface NotificationRecordOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.NotificationRecord)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string notification_id = 1;</code>
   * @return The notificationId.
   */
  java.lang.String getNotificationId();
  /**
   * <code>string notification_id = 1;</code>
   * @return The bytes for notificationId.
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();

  /**
   * <code>int64 order_id = 2;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string timestamp = 4;</code>
   * @return The timestamp.
   */
  java.lang.String getTimestamp();
  /**
   * <code>string timestamp = 4;</code>
   * @return The bytes for timestamp.
   */
  com.google.protobuf.ByteString
      getTimestampBytes();

  /**
   * <code>string status = 5;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 5;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
