// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public interface OrderNotificationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.OrderNotificationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string notification_id = 3;</code>
   * @return The notificationId.
   */
  java.lang.String getNotificationId();
  /**
   * <code>string notification_id = 3;</code>
   * @return The bytes for notificationId.
   */
  com.google.protobuf.ByteString
      getNotificationIdBytes();
}
