// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: notification.proto

// Protobuf Java Version: 3.25.1
package com.example.notification;

public interface OrderNotificationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notification.OrderNotificationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 order_id = 1;</code>
   * @return The orderId.
   */
  long getOrderId();

  /**
   * <code>int64 client_id = 2;</code>
   * @return The clientId.
   */
  long getClientId();

  /**
   * <code>string client_name = 3;</code>
   * @return The clientName.
   */
  java.lang.String getClientName();
  /**
   * <code>string client_name = 3;</code>
   * @return The bytes for clientName.
   */
  com.google.protobuf.ByteString
      getClientNameBytes();

  /**
   * <code>string client_email = 4;</code>
   * @return The clientEmail.
   */
  java.lang.String getClientEmail();
  /**
   * <code>string client_email = 4;</code>
   * @return The bytes for clientEmail.
   */
  com.google.protobuf.ByteString
      getClientEmailBytes();

  /**
   * <code>double total_amount = 5;</code>
   * @return The totalAmount.
   */
  double getTotalAmount();

  /**
   * <code>string status = 6;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 6;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 7;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 7;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
